// This file is generated by Gemini.
'use server';

/**
 * @fileOverview Simulates the impact of adding a new skill to a user's profile.
 *
 * - simulateNewSkillsImpact - A function that simulates the impact of adding a new skill.
 * - SimulateNewSkillsImpactInput - The input type for the simulateNewSkillsImpact function.
 * - SimulateNewSkillsImpactOutput - The return type for the simulateNewSkillsImpact function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SimulateNewSkillsImpactInputSchema = z.object({
  existingSkills: z
    .string()
    .describe('A comma-separated list of the user\'s existing skills.'),
  newSkill: z.string().describe('The new skill to simulate adding.'),
  interests: z
    .string()
    .describe('A comma-separated list of the user\'s interests.'),
  workExperience: z
    .string()
    .describe('A brief description of the user\'s work experience.'),
});
export type SimulateNewSkillsImpactInput = z.infer<
  typeof SimulateNewSkillsImpactInputSchema
>;

const SimulateNewSkillsImpactOutputSchema = z.object({
  potentialJobs: z
    .string()
    .describe(
      'A comma-separated list of potential job titles that the user could pursue with the new skill.'
    ),
  demandImpact: z
    .string()
    .describe(
      'A brief description of the potential impact on job demand with the new skill.'
    ),
  salaryRange: z
    .string()
    .describe(
      'An estimated salary range for jobs that require the new skill.'
    ),
});
export type SimulateNewSkillsImpactOutput = z.infer<
  typeof SimulateNewSkillsImpactOutputSchema
>;

export async function simulateNewSkillsImpact(
  input: SimulateNewSkillsImpactInput
): Promise<SimulateNewSkillsImpactOutput> {
  return simulateNewSkillsImpactFlow(input);
}

const prompt = ai.definePrompt({
  name: 'simulateNewSkillsImpactPrompt',
  input: {schema: SimulateNewSkillsImpactInputSchema},
  output: {schema: SimulateNewSkillsImpactOutputSchema},
  prompt: `You are a career counselor. A user wants to understand how adding a new skill to their profile might affect their future job opportunities.

  Based on the user's existing skills, interests, and work experience, and the new skill they are considering, suggest potential job titles, the potential impact on job demand, and an estimated salary range.

  Existing Skills: {{{existingSkills}}}
  New Skill: {{{newSkill}}}
  Interests: {{{interests}}}
  Work Experience: {{{workExperience}}}

  Respond in a way that is easily parseable.
  `,
});

const simulateNewSkillsImpactFlow = ai.defineFlow(
  {
    name: 'simulateNewSkillsImpactFlow',
    inputSchema: SimulateNewSkillsImpactInputSchema,
    outputSchema: SimulateNewSkillsImpactOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
